version: "3.12"

services:
  model:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    env_file:
      - .env
    command: ["python3", "cli.py"]
    container_name: gemini-rag-model
    ports:
      - "8000:8000"
    volumes:
      - ./model:/model:cached
      - ./.env:/model/.env:ro
      - ./service-account.json:/model/service-account.json:ro
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_REGION=${GEMINI_REGION}
      - GOOGLE_APPLICATION_CREDENTIALS=/model/service-account.json
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_LOCATION=${GCP_LOCATION}
      - USE_VERTEX_AI=${USE_VERTEX_AI}
      - GEMINI_FLASH_MODEL_NAME=${GEMINI_FLASH_MODEL_NAME}
      - GEMINI_PRO_MODEL_NAME=${GEMINI_PRO_MODEL_NAME}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO_OWNER=${GITHUB_REPO_OWNER}
      - GITHUB_REPO_NAME=${GITHUB_REPO_NAME}
      - GITHUB_BRANCH_NAME=${GITHUB_BRANCH_NAME}
      - CHROMA_COLLECTION_NAME=${CHROMA_COLLECTION_NAME}
      - CHROMA_DB_PATH=${CHROMA_DB_PATH}
    
    networks:
      - public_network
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  public_network:
    driver: bridge